# 3. Task: Retirement Age Calculator
# ● Objective: Write a program that prompts the user for their age and tells them how
# many years until they reach retirement age (65).
# ● Hints:
# ○ Ask the user to input their age.
# ○ Calculate how many more years they have until they reach 65 years of
# age.
# ○ Display the number of years left until retirement or a message if the user
# has already reached retirement age.

age=int(input("ENTER YOUR AGE :"))
retirement_age=65
years = retirement_age - age

if years > 0:
    print(f"YOU HAVE {years} YEARS LEFT IN RETIREMENT ")
elif:
    years< 0
    print("YOU HAVE REACHED YOUR RETIREMENT")
